### ISSUE TITLE
Add a column to an ASCII file

### ISSUE THREAD

**Issue by SelimRaboudi** [djvanderlaan/LaF#7]
Hi Jan,

I'd like to add a column to a large ascii file, as a combination of multiple columns (ex: sum of 2 variables on the same row). Basically before the operation the csv file will look like this:

var1, var2
1, 2
3,3
....

and after it will look like this:

var1, var2, var3
1, 2, 3
3,3, 6
....

So my questions are:
- is this currently possible to do in LaF ?
- If not, do you think it's still feasible ?

**Comment by djvanderlaan** [comment]
Hi @SelimRaboudi,

`LaF` can only read files. It does not contain any code for writing files. The only way to handle your problem is to read your file (possibly in chunks it its large), add the new column(s) and then write data back to a new file. 

Fortunately, a colleague of mine has written a package that makes this easier: [chunked](https://github.com/edwindj/chunked). 

Example:

```R
# Generate example file
data <- data.frame(a = 1:1E7, b = 1:1E7)
write.csv(data, "input.csv", row.names=FALSE)

#Install chunked:
# devtools::install_github('edwindj/chunked')


library(LaF)
library(chunked)

# Read from input.csv; add column; and write to output.csv
read_csv_chunkwise("input.csv", chunk_size=5000) %>% 
  mutate(c = a + b) %>% 
  write_csv_chunkwise("./output.csv")
```
